// Built-in profanity packs used by the content script. All entries are lowercase for simpler matching.
// Packs aim to cover common profane phrases while avoiding slurs unless broadly recognized.

export const PROFANITY_PACKS = {
    strong: [
        'fuck',
        'fucking',
        'fucker',
        'motherfucker',
        'shit',
        'bullshit',
        'bitch',
        'son of a bitch',
        'asshole',
        'jackass',
        'dick',
        'dickhead',
        'pissed',
        'piss off',
        'goddamn',
        'god damn',
        'damn it',
        'bastard',
        'douche',
        'douchebag',
        'cunt',
        'crapface'
    ],
    mild: [
        'crap',
        'crud',
        'dang',
        'darn',
        'heck',
        'shoot',
        'frick',
        'fricking',
        'friggin',
        'screw',
        'screwed',
        'sucks',
        'suck',
        'butthead',
        'butt',
        'idiot',
        'moron',
        'jerk',
        'loser',
        'stupid',
        'tool',
        'weirdo'
    ],
    blasphemy: [
        'oh my god',
        'omg',
        'oh my gosh',
        'oh my goodness',
        'good lord',
        'lord above',
        'lord have mercy',
        'for god sake',
        "for god's sake",
        'for gods sake',
        'for goodness sake',
        'for heavens sake',
        'jesus',
        'jesus christ',
        'christ almighty',
        'sweet jesus',
        'holy cow',
        'holy crap',
        'holy smokes',
        'holy moly',
        'i swear to god',
        'swear to god'
    ]
};
